### ISSUE TITLE
[Failed Build]: SSLError

### ISSUE THREAD

**Issue by ILScratchLittleAC** [MatteoH2O1999/setup-python#56] opened 2024-12-02 10:55 UTC
### CPython version

2.7

### Failed labels

macos-latest

### Used runners

Github-hosted

### Failed build logs

https://github.com/ILScratchLittleAC/BilibiliVideoDownload-Playground/actions/runs/12117349441/job/33780205174

**Comment by MatteoH2O1999** [comment] 2024-12-02 22:46
Hey, thank you for opening this issue.
Unfortunately what you are experiencing is caused by the fact that there is no build for SSL 1.0.2 on `macos-latest` anymore.
You could probably get away with it using an older macos label, like `macos-12` or `macos-13`.
Unfortunately, that puts a timer on it, so be aware that in the near future you won't be able to use Python 2.7 and should update it  to >= 3.9.
Note how this is also written in your [build logs](https://github.com/ILScratchLittleAC/BilibiliVideoDownload-Playground/actions/runs/12117349441/job/33780205174#step:6:25), where this action tries to warn you that the fact you could manage to build 2.7 from source is more due to luck than support.

I'm going to close this as Python 2.7 is EOL, and as written [here](https://github.com/MatteoH2O1999/setup-python?tab=readme-ov-file#motivation), I won't break support intentionally but won't spend time and resources in fighting a losing battle against time.

**Closed by MatteoH2O1999** 2024-12-02 22:46 UTC
Labels: bug
