### ISSUE TITLE
Python not found - probably not added automatically to PATH ?

### ISSUE THREAD

**Issue by smarie** [MatteoH2O1999/setup-python#28] opened 2023-10-01 14:36 UTC
Hi, thanks for the great tool !

I am the author of https://github.com/smarie/python-pytest-cases, and I recently switched my nox virtual environment backend from conda to virtualenv. This requires direct installation of python (not through conda anymore)

I tried to use your action but it does not behave exactly as `setup-python` :

 - this fails: https://github.com/smarie/python-pytest-cases/actions/runs/6371035936/job/17292643321
 - this works: https://github.com/smarie/python-pytest-cases/actions/runs/6371035936/job/17292644022

I suspect that there is a missing registration with the PATH, I am currently experimenting about that. If I confirm that this solves the issue, it could probably be a great additional parameter to add in order to be as close as possible with the behaviour of setup-python

EDIT: adding to PATH does not solve the issue as shown here: https://github.com/smarie/python-pytest-cases/actions/runs/6371356100/job/17293226935#step:4:10

```bash
nox > Command /opt/hostedtoolcache/Python/3.9.18/x64/bin/python -m virtualenv /home/<...> -p python3.5 failed with exit code 1:
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.5'
```

Maybe virtualenv uses a different way to see the list of python versions available ? I'll have to spend more time to understand. Maybe there is something to register with `py`

**Comment by MatteoH2O1999** [comment] 2023-10-02 14:39
> If I confirm that this solves the issue, it could probably be a great additional parameter to add in order to be as close as possible with the behaviour of setup-python

The problem with this is that this action actually calls [setup-python](https://github.com/actions/setup-python) to perform the update of the environment variables.

Just to confirm, try to add this step before calling nox and remove the one adding python to PATH:
```yml
- run: |
    import os
    import shutil
    print('\n'.join(os.environ['PATH'].split(os.pathsep)))
    print('-----------------------')
    print(shutil.which('python'))
    print(shutil.which('python3'))
    print(shutil.which('python3.5'))
  shell: python
```

**Comment by MatteoH2O1999** [comment] 2023-10-03 15:04
As you can see [here](https://github.com/smarie/python-pytest-cases/actions/runs/6392273566/job/17349209050#step:6:41) the correct python is actually detected. This looks more like a nox configuration problem to me

**Comment by smarie** [comment] 2023-10-03 16:03
Actually `nox` is just calling `virtualenv`, which uses its own strategies to detect available python versions. I suspect that this is where the link is missing. I will rerun with explicit virtualenv call

**Comment by MatteoH2O1999** [comment] 2023-10-03 19:42
Just checked it in a fork. The problem is virtualenv for Python 3.9 is no longer compatible with 3.5 and 2.7.
While querying the executables it uses syntax that 3.5 and 2.7 do not support anymore.
Try adding `virtualenv==20.15.1` to your requirements file and it should no longer be an issue.
Closing this as it is seems to me not to be caused by this action.

Feel free to reopen if you still think this action is causing the issue.

**Closed by MatteoH2O1999** 2023-10-03 19:42 UTC

**Comment by smarie** [comment] 2023-10-03 19:46
Thanks @MatteoH2O1999 ! I'll test this

**Comment by smarie** [comment] 2023-10-04 08:12
It seems that your solution works ! 
https://github.com/smarie/python-pytest-cases/actions/runs/6397701763

Thanks @MatteoH2O1999 , I really appreciate your help
